### ISSUE TITLE
How to handle Success or Failure Response from inside app

### ISSUE THREAD

**Issue by boggerapp** [RemitaNet/remita-android#1]
How do one handle callbacks for user transactions? I could see we need to pass returnUrl to the SDK just like the web but no handler is requested for SUCCESS or FAILURE action for the app. when a user makes a payment, there is no way the app could tell whether it was successful or not in other to perform further actions. 
This SDK is close to useless for a native app!

**Comment by toolzskillz** [comment]
Hello @boggerapp Please we've updated our github repository to make your integration(s) more seamless.

Thanks
